// create order constants
export const CREATE_ORDER_REQUEST = 'CREATE_ORDER_REQUEST';
export const CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS';
export const CREATE_ORDER_FAIL = 'CREATE_ORDER_FAIL';

// get user orders constants
export const USER_ORDER_REQUEST = 'USER_ORDER_REQUEST';
export const USER_ORDER_SUCCESS = 'USER_ORDER_SUCCESS';
export const USER_ORDER_FAIL = 'USER_ORDER_FAIL';

// get order Details
export const ORDER_DETAILS_REQUEST = 'ORDER_DETAILS_REQUEST';
export const ORDER_DETAILS_SUCCESS = 'ORDER_DETAILS_SUCCESS';
export const ORDER_DETAILS_FAIL = 'ORDER_DETAILS_FAIL';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';
