// constants to get products
export const ALL_PRODUCTS_REQUEST = 'ALL_PRODUCTS_REQUEST';
export const ALL_PRODUCTS_SUCCESS = 'ALL_PRODUCTS_SUCCESS';
export const ALL_PRODUCTS_FAIL = 'ALL_PRODUCTS_FAIL';

// constants to get product details
export const PRODUCTS_DETAILS_REQUEST = 'PRODUCTS_DETAILS_REQUEST';
export const PRODUCTS_DETAILS_SUCCESS = 'PRODUCTS_DETAILS_SUCCESS';
export const PRODUCTS_DETAILS_FAIL = 'PRODUCTS_DETAILS_FAIL';

// clear error
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
