// constants to get products
export const ALL_PRODUCTS_REQUEST = 'ALL_PRODUCTS_REQUEST';
export const ALL_PRODUCTS_SUCCESS = 'ALL_PRODUCTS_SUCCESS';
export const ALL_PRODUCTS_FAIL = 'ALL_PRODUCTS_FAIL';

// constants to get product details
export const PRODUCTS_DETAILS_REQUEST = 'PRODUCTS_DETAILS_REQUEST';
export const PRODUCTS_DETAILS_SUCCESS = 'PRODUCTS_DETAILS_SUCCESS';
export const PRODUCTS_DETAILS_FAIL = 'PRODUCTS_DETAILS_FAIL';

// Review Constants

export const NEW_REVIEW_REQUEST = 'NEW_REVIEW_REQUEST';
export const NEW_REVIEW_SUCCESS = 'NEW_REVIEW_SUCCESS';
export const NEW_REVIEW_RESET = 'NEW_REVIEW_RESET';
export const NEW_REVIEW_FAIL = 'NEW_REVIEW_FAIL';

// clear error
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
